-- Supabase Compatible - Full Clean Schema - Fixes 42710 type already exists
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS analytics_snapshots CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS sustainability_metrics CASCADE;
DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS staff_assignments CASCADE;
DROP TABLE IF EXISTS staff CASCADE;
DROP TABLE IF EXISTS incidents CASCADE;
DROP TABLE IF EXISTS crowd_metrics CASCADE;
DROP TABLE IF EXISTS zones CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS stadiums CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP VIEW IF EXISTS v_zone_occupancy_status CASCADE;
DROP VIEW IF EXISTS v_active_incidents CASCADE;
DROP VIEW IF EXISTS v_event_summary CASCADE;
DROP VIEW IF EXISTS v_staff_on_duty CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;
DROP TYPE IF EXISTS incident_severity CASCADE;
DROP TYPE IF EXISTS incident_status CASCADE;
DROP TYPE IF EXISTS incident_type CASCADE;
DROP TYPE IF EXISTS zone_type CASCADE;
DROP TYPE IF EXISTS zone_status CASCADE;
DROP TYPE IF EXISTS notification_type CASCADE;
DROP TYPE IF EXISTS event_status CASCADE;
DROP TYPE IF EXISTS sustainability_category CASCADE;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE TYPE user_role AS ENUM ('admin', 'manager', 'staff', 'security', 'medical', 'viewer', 'fan');
CREATE TYPE incident_severity AS ENUM ('low', 'medium', 'high', 'critical');
CREATE TYPE incident_status AS ENUM ('reported', 'acknowledged', 'in_progress', 'resolved', 'closed');
CREATE TYPE incident_type AS ENUM ('medical', 'security', 'crowd', 'technical', 'safety', 'weather', 'other');
CREATE TYPE zone_type AS ENUM ('entrance', 'exit', 'seating', 'concourse', 'concession', 'restroom', 'vip', 'media', 'field', 'parking', 'medical', 'security');
CREATE TYPE zone_status AS ENUM ('open', 'closed', 'restricted', 'evacuation', 'maintenance');
CREATE TYPE notification_type AS ENUM ('info', 'warning', 'critical', 'emergency', 'update');
CREATE TYPE event_status AS ENUM ('scheduled', 'live', 'halftime', 'completed', 'cancelled', 'postponed');
CREATE TYPE sustainability_category AS ENUM ('transport', 'waste', 'energy', 'water', 'food');
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), email VARCHAR(255) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, role user_role NOT NULL DEFAULT 'staff', is_active BOOLEAN DEFAULT TRUE, is_verified BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE stadiums (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name VARCHAR(255) NOT NULL, city VARCHAR(100) NOT NULL, capacity INTEGER NOT NULL CHECK (capacity > 0), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE events (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), stadium_id UUID NOT NULL REFERENCES stadiums(id) ON DELETE CASCADE, name VARCHAR(255) NOT NULL, start_time TIMESTAMPTZ NOT NULL, status event_status DEFAULT 'scheduled', expected_attendance INTEGER, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE zones (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), stadium_id UUID NOT NULL REFERENCES stadiums(id) ON DELETE CASCADE, name VARCHAR(255) NOT NULL, code VARCHAR(50) NOT NULL, type zone_type NOT NULL, status zone_status DEFAULT 'open', capacity INTEGER NOT NULL, current_occupancy INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(stadium_id, code));
CREATE TABLE crowd_metrics (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), stadium_id UUID NOT NULL REFERENCES stadiums(id) ON DELETE CASCADE, zone_id UUID NOT NULL REFERENCES zones(id) ON DELETE CASCADE, event_id UUID REFERENCES events(id) ON DELETE SET NULL, timestamp TIMESTAMPTZ DEFAULT NOW(), density DECIMAL(5,2), occupancy_count INTEGER NOT NULL, risk_score DECIMAL(3,2), is_anomaly BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE incidents (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), stadium_id UUID NOT NULL REFERENCES stadiums(id) ON DELETE CASCADE, zone_id UUID REFERENCES zones(id) ON DELETE SET NULL, event_id UUID REFERENCES events(id) ON DELETE SET NULL, type incident_type NOT NULL, severity incident_severity NOT NULL DEFAULT 'medium', status incident_status DEFAULT 'reported', title VARCHAR(255) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE staff (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, stadium_id UUID NOT NULL REFERENCES stadiums(id) ON DELETE CASCADE, employee_id VARCHAR(50) UNIQUE NOT NULL, department VARCHAR(100) NOT NULL, is_on_duty BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE staff_assignments (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), staff_id UUID NOT NULL REFERENCES staff(id) ON DELETE CASCADE, stadium_id UUID NOT NULL REFERENCES stadiums(id) ON DELETE CASCADE, task_title VARCHAR(255) NOT NULL, start_time TIMESTAMPTZ NOT NULL, end_time TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE notifications (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), stadium_id UUID REFERENCES stadiums(id) ON DELETE CASCADE, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, type notification_type NOT NULL DEFAULT 'info', is_read BOOLEAN DEFAULT FALSE, is_broadcast BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE chat_messages (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), session_id VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant', 'system')), message TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE sustainability_metrics (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), stadium_id UUID NOT NULL REFERENCES stadiums(id) ON DELETE CASCADE, category sustainability_category NOT NULL, metric_name VARCHAR(100) NOT NULL, value DECIMAL(12,2) NOT NULL, unit VARCHAR(50) NOT NULL, eco_points INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE tickets (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE, stadium_id UUID NOT NULL REFERENCES stadiums(id) ON DELETE CASCADE, ticket_code VARCHAR(100) UNIQUE NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE analytics_snapshots (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), stadium_id UUID NOT NULL REFERENCES stadiums(id) ON DELETE CASCADE, snapshot_type VARCHAR(50) NOT NULL, period_start TIMESTAMPTZ NOT NULL, period_end TIMESTAMPTZ NOT NULL, kpis JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE audit_logs (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), action VARCHAR(100) NOT NULL, table_name VARCHAR(100) NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
INSERT INTO stadiums (name, city, capacity) VALUES ('MetLife Stadium', 'East Rutherford', 82500), ('SoFi Stadium', 'Inglewood', 70000) ON CONFLICT DO NOTHING;
INSERT INTO users (email, password_hash, first_name, last_name, role, is_verified) VALUES ('admin@fifa2026.com', crypt('Admin123!@#', gen_salt('bf')), 'System', 'Administrator', 'admin', true) ON CONFLICT (email) DO NOTHING;
